### ISSUE TITLE
Wonky d3-array injection

### ISSUE THREAD

**Issue by curran** [d3/d3-tile#1]
The build seems to be trying to inject d3-array (a dependency of d3-tile) in a strange way.

Currently, the first few lines of the built file look like this:

```js
1. (function (global, factory) {
2.   typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('d3-array')) :
3.   typeof define === 'function' && define.amd ? define(['exports', 'd3-array'], factory) :
4.   (factory((global.d3 = global.d3 || {}),global.d3Array));
5. }(this, function (exports,d3Array) { 'use strict';
```

In the browser, this throws an error when trying to resolve `global.d3Array`.

To get this to work inside [Raster & Vector 4.0](http://bl.ocks.org/curran/e857dbe6db49d4cac379855b0b6b58e9), I ended up manually changing line 4 to be:

```js
(factory((global.d3 = global.d3 || {}),global.d3));
```

This works fine. Any ideas on how to make the build generate this?

**Comment by mbostock** [comment]
I fixed this in 0.0.3. Whenever you add a dependency on another D3 module, you need to update the `-g` argument to Rollup to tell it to use the global `d3` in a vanilla environment:

```
rollup -g d3-array:d3 …
```

If you don’t, then Rollup by default converts the hyphenated npm module name (“d3-array”) to a lower camel-cased name (“d3Array”).
