### ISSUE TITLE
Rename tile.x and tile.y to tile.tx and tile.ty?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-tile#15]
I feel like the distinction between tile[0] and tile.x is too small (or that the names are easily confused), especially since typically we substitute tile[0] as the %x variable in a URL template.

Maybe the names *tile*.tx and *tile*.ty would be better? Especially if they are premultiplied? Although I guess d3.zoomTransform uses {x, y, k}, so, I dunno.

**Comment by curran** [comment]
I'm down to rename tile.x and tile.y to tile.tx and tile.ty.

From the outset I kind of felt the array representation was a bit opaque. If we're using named properties for `tx` and `ty`, it almost feels like the whole thing should just be an object with named properties only. That might be simpler for newcomers to grok, rather than having an array with properties, which may be confusing.

What are your thoughts on this idea:

```
var d = {
  x: 1, // previously d[0]
  y: 5, // previously d[1]
  z: 4, // previously d[2] - naming in line with the URL templates in the Leaflet world
  tx: 256, // x * 256 with wrapping logic applied
  tz: 1280 // y * 256
};
```

**Comment by curran** [comment]
I've made two PRs for two alternative representations. Which do you prefer?

 * Rename tile.x and tile.y to tile.tx and tile.ty #19
 * Tile array to object #20

**Comment by mbostock** [comment]
The object seems like the simplest approach, yeah. I can’t think of any great wins by using the array representation. Sometimes it’s nice to use arrays for 2D points because the default toString behavior on [*x*, *y*] can be embedded into a transform, such as `"translate(" + point + ")"`. But that’s not the case here.

**Comment by curran** [comment]
Right, I thought of string generation too as one possible win for the array.

If the ordering were `[z, x, y]`, the the URL could look like this:

```js
"http://" + "abc"[d[1] % 3] + ".tile.openstreetmap.org/" + d.join("/") + ".png"; })
```

But even here, I think I would prefer to see:

```js
"http://" + "abc"[d[1] % 3] + ".tile.openstreetmap.org/" + d.z + "/" + d.x + "/" + d.y + ".png"; })
```

I'll move ahead with the object version (#20) and merge it once documentation is updated.
