### ISSUE TITLE
Size should return (x1-x0, y1-y0) not (x1, y1)

### ISSUE THREAD

**Issue by curran** [d3/d3-tile#17]
I was going about building out the tests and I encountered this:

```js
var tileLayout = d3.tile().extent([[100, 200], [300, 350]]);
test.deepEqual(tileLayout.size(), [200, 150]); // Currently fails - actual: [ 300, 350 ]
```

In the source, tile.size() is returning (x1, y1):

```js
tile.size = function(_) {
  return arguments.length ? ... : [x1, y1];
};
```

Perhaps it should be changed to return (x1-x0, y1-y0)?

```js
tile.size = function(_) {
  return arguments.length ? ... : [x1 - x0, y1 - y0];
};
```

**Comment by mbostock** [comment]
The same design applies to [*voronoi*.size](https://github.com/d3/d3-voronoi#voronoi_size).

I guess it’s more reasonable to return the difference. The reason I did it the other way is that when you set the size, the top-left is always [0,0], so the returned size is equivalent assuming that you are using *voronoi*.size consistently to both set and get. But your interpretation is more reasonable if you are mixing them together.

**Comment by curran** [comment]
Ahh great, I see you made the change in d3-voronoi, so I'll go ahead and merge #18 to change it over here too.
