### ISSUE TITLE
The tile size should be configurable.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-tile#22]
It currently is limited to 256, which is a reasonable default, but any power of two square should be reasonable. (Instances of 8 in the code probably refer to Math.log2(_tileSize_).) In theory any width and height would also be possible but I think that generalization would make the code more complicated than necessary for now.

**Comment by curran** [comment]
It would be great if we can find some examples of tile providers that are not 256 X 256 for testing against.

I came across this [section of the OpenStreetMap docs](http://wiki.openstreetmap.org/wiki/Tiles#Graphical_Map_Tiles):

> Map tiles are typically 256×256 pixel images. ... Tiles are not always in these dimensions; for example there could be 64×64 pixel images for mobile use, however 256×256 pixel images are a de facto standard. 515×512 pixel seems to be the usual size of high-resolution tiles.

There's also an interesting [page on "meta-tiles"](http://wiki.openstreetmap.org/wiki/Meta_tiles), which could be 2048x2048.

After some searching I have not found an actual tile provider that yields other than 256×256 tiles. Will post again here if I find one.

**Comment by linusmarco** [comment]
Mapzen's API serves up 512x512 tiles: 
https://mapzen.com/documentation/vector-tiles/use-service/#specify-tile-size

I'll take a stab at implementing configurable tile sizes (keeping default as 256).
