### ISSUE TITLE
Image API

### ISSUE THREAD

**Issue by curran** [d3/d3-tile#3]
Copied from https://github.com/d3/d3-geo/issues/35

There's room for building a higher level module on top of the existing tile code for working with images. Currently each of the [examples](https://github.com/d3/d3-plugins/tree/master/geo/tile#zoomable-tiles) re-implements image loading logic separately, along the lines of the following (from [Raster & Vector II](http://bl.ocks.org/mbostock/5342063)):

``` js
var raster = svg.append("g");
...
function zoomed() {
  ...
  var image = raster
      .attr("transform", "scale(" + tiles.scale + ")translate(" + tiles.translate + ")")
    .selectAll("image")
      .data(tiles, function(d) { return d; });

  image.exit()
      .remove();

  image.enter().append("image")
      .attr("xlink:href", function(d) { return "http://" + ["a", "b", "c"][Math.random() * 3 | 0] + ".tile.openstreetmap.org/" + d[2] + "/" + d[0] + "/" + d[1] + ".png"; })
      .attr("width", 1)
      .attr("height", 1)
      .attr("x", function(d) { return d[0]; })
      .attr("y", function(d) { return d[1]; });
}
```

I wonder if it might make sense to try to encapsulate this logic into an API similar to that of [Leaflet](http://leafletjs.com/). The API could take as input the `raster` g element and A URL pattern for tiles, and expose methods for setting the scale and translate. Examples of features that could be added into such a module include:
- Tile URL template strings like `'http://{s}.tile.osm.org/{z}/{x}/{y}.png'`. This would make it easy to use different tile providers based on declarative data, like in this [Leaflet Providers Demo](https://leaflet-extras.github.io/leaflet-providers/preview/).
  - Caching tiles. As an example, [Raster & Vector II](http://bl.ocks.org/mbostock/5342063) has the behavior of re-loading the same tiles again and again, due to the randomness introduced in the URL generation. I think this issue would be solved by deterministic URL generation, leaving the actual caching up to the browser.
- Showing larger, blurry tiles in the background as smaller tiles load in the foreground. This would vastly improve the user experience when zooming. The current behavior in the examples is that the larger tiles disappear, and the user is looking at empty white space until the higher zoom level tiles are loaded. This would however introduce complexity to the code. The exiting of tiles would be contingent upon all of their "child" tiles having loaded.

**Comment by curran** [comment]
I did some experimenting towards the blurry background tiles concept, and realized that `tiles.scale` and `tiles.translate` changes completely based on the zoom level. Having the blurry tiles in the background until all of their quadtree children are finished loading requires that we can compute the scale and translate for those tiles that are no longer returned from the tile layout.

Maybe instead of having `tiles.scale` and `tiles.translate` attached to the returned array, the logic for computing those values could go into a function that takes the tile address as input and returns the transform as output on a per-tile basis. This could be something like `tile.transformForTile(address)`, returning a zoom transform.

We'll also need to listen for when tiles load. The following works for this:

```js
image.enter().append("image")
    .attr("xlink:href", function(d) { ... })
    .on("load", function (d){
      // If this tile is no longer included in the output from the layout,
      // and all of its 4 "children" tiles are loaded,
      // Then remove it from the set of displayed tiles.
    });
```

In addition, the tiles that are displayed will need to be managed. One idea I had for doing this is to use a Set like this:

```js
var tilesSet = d3.set();
tile
  .scale(transform.k)
  .translate([transform.x, transform.y])
  ()
  .forEach(function (d){
    tilesSet.add(JSON.stringify(d));
  }); 
```

The tile addresses could be recovered like this:

```js
var tileAddresses = tilesSet.values().map(JSON.parse);
```

**Comment by mbostock** [comment]
Closing this to inactivity, and also because it feels like a higher-level API might belong better as a separate module.
