### ISSUE TITLE
The function `wrap()` does not work as expected

### ISSUE THREAD

**Issue by photino** [d3/d3-tile#32]
The doc says that **If wrap is specified, sets this tile layout’s wrapping option to the specified boolean value and returns this tile layout**, however it does not work as expected. Do we have some tests or examples for the `wrap()` function?

**Comment by curran** [comment]
Could you please post an example that reproduces the behavior you see?

**Comment by photino** [comment]
@curran Sorry, my `d3-tile` is an old version 0.0.3. The latest version works as expected.
