### ISSUE TITLE
Usage with `import`

### ISSUE THREAD

**Issue by guigrpa** [d3/d3-tile#39]
I think the documentation should include usage instructions when importing d3 as an ES6 module:

```js
import * as d3 from 'd3';
```

How is d3-tile to be imported?

**Comment by mbostock** [comment]
The recommended pattern is to not use the D3 default bundle (d3/d3) when using ES modules. Instead, use the individual [D3 modules](https://github.com/d3), and import the specific symbols you need to use.

```js
import {tile} from "d3-tile";
```

If you want to import a module as a namespace, you must define a separate namespace for each module.

```js
import * as d3 from "d3";
import * as d3Tile from "d3-tile";
```

Then you can say `d3Tile.tile`.

**Comment by guigrpa** [comment]
Thanks for the insight, and in general for the work of art that is d3.

Maybe that should appear somewhere in the docs…

**Comment by mbostock** [comment]
Add some language here: https://github.com/d3/d3/wiki#supported-environments

The wiki is publicly-editable and contributions are welcome.
