### ISSUE TITLE
v0.0.4 breaks examples in documentation that use v0.0.3

### ISSUE THREAD

**Issue by clhenrick** [d3/d3-tile#40]
I noticed that the Unkpg CDN link in the README:

```
https://unpkg.com/d3-tile@0.0
```

is for `v0.0.4`, however the library used in the examples in the README,

```
//d3js.org/d3-tile.v0.0.min.js
```
is for `v0.0.3` of the library. 

If I attempt to use the `v0.0.4` version, the examples break. Reading over the API docs for this library I was not able to yet debug why it is breaking them.

**Comment by clhenrick** [comment]
Upon further investigation it looks like this is because `v0.0.4` changed the data structure returned by `tiles`.

Previously that data consisted of a two dimensional array, but `v0.0.4` returns an array of objects. It would be helpful to update the example blocks that are linked to in the documentation to reflect this change.

**Comment by curran** [comment]
Closing in favor of #52
