### ISSUE TITLE
d3.event.transform has x and y NaN

### ISSUE THREAD

**Issue by oufresh** [d3/d3-tile#43]
Hello,

I opened the issue in d3-zoom but I think it's better here.

I'm trying to do something like this example:

http://bl.ocks.org/mbostock/5914438

using the current these version:
d3: 5.5.0
d3-tile: 0.0.4

and installing the packages with npm.
I have these imports:

import * as d3 from 'd3';
import * as d3Tile from "d3-tile";
import * as topojson from 'topojson';

When the data are loaded and the function zoomed is called, this part of code ha sa problem:

var transform = d3.event.transform;

transform.x and transform.y are 'NaN'

All the code is basically here. I only changed in the callback function for retrieving data from OSM the d parameter that is no more an array but an object.

stringify(scale: number, translate: Array<number>): string
{
    var k = scale / 256, r = scale % 1 ? Number : Math.round;
    return "translate(" + r(translate[0] * scale) + "," + r(translate[1] * scale) + ") scale(" + k + ")";
}

  
zoomed()
{
    var transform = d3.event.transform;

    var tiles = this.tile
        .scale(transform.k)
        .translate([transform.x, transform.y])
        ();
  
    this.vector
        .attr("transform", transform)
        .style("stroke-width", 1 / transform.k);
  
    var image = this.raster
        .attr("transform", this.stringify(tiles.scale, tiles.translate))
      .selectAll("image")
      .data(tiles, function(d) { return d; });
  
    image.exit().remove();
  
    image.enter().append("image")
        .attr("xlink:href", function(d) { return "http://" + "abc"[d.x % 3] + ".tile.openstreetmap.org/" + d.z + "/" + d.x + "/" + d.y + ".png"; })
        .attr("x", function(d) { return d.x * 256; }) 
        .attr("y", function(d) { return d.y * 256; })
        .attr("width", 256)
        .attr("height", 256);
}

_initV()
{
    const width = this.svgCanvas.clientWidth;
    const height = this.svgCanvas.clientHeight;

    const projection = d3.geoMercator()
        .scale(1 / (2*Math.PI))
        .translate([0, 0]);

    var path = d3.geoPath()
        .projection(projection);

    this.tile = d3Tile.tile()
        .size([width, height]);
    
    var zoom = d3Zoom.zoom()
        .scaleExtent([1 << 11, 1 << 14])
        .on("zoom", this.zoomed);

    this.svg = d3.select("svg")
        .attr("width", width)
        .attr("height", height);

    this.raster = this.svg.append("g");

    this.vector = this.svg.append("path");

    fetch('http://localhost:8080/us.json').then(resp => {
            if (resp.ok)
                return resp.json();
            else {
                console.error(resp.statusText);
                throw new Error('Response error');
            }
        }).then(us => {
            var center = projection([-98.5, 39.5]);

            this.svg
                .call(zoom)
                .call(zoom.transform, d3.zoomIdentity
                .translate(width / 2, height / 2)
                .scale(1 << 12)
                .translate(-center[0], -center[1]));
            

            this.vector
                .attr("d", path(topojson.mesh(us, us.objects.counties)));
        }).catch(error => {
            console.error(error);
    });
}

I tried the same code with a standalone html file and it works correctly. It doesn't if I use npm and the imports with webpack.

Many thanks.

**Comment by linusmarco** [comment]
I'll note that this has nothing to do with d3-tile, but here's your answer:

First, `d3-zoom` is included in the main `d3` npm package, so you don't need to import it separately. This line:
```js
var zoom = d3Zoom.zoom()
```
can be changed to:
```js
var zoom = d3.zoom()
```
and your problem should be fixed.

Alternatively, if you want to import d3-zoom separately for whatever reason (I assume if you're doing that you're probably doing it for bundle size reduction, so you'd want to do that for every d3 submodule you use), I think the syntax you want is:
```js
var zoom = d3Zoom()
```

**Comment by oufresh** [comment]
Thank you for your response. It worked without including d3-zoom.
Yes, in the future I would like to optimize the bundle size.

Just a suggestion, is it possible to update the example on the d3-tile page?

**Comment by linusmarco** [comment]
Great!

Can you elaborate on what updates you are suggesting? There are several examples in the README.

**Comment by oufresh** [comment]
Excuse me,
I have some doubt:

1. Are there some description how the scale in d3-zoom and d3-tile works? I see that the tiles generated by  d3-tile has the slippy Map convention but wich is the scale?

2. Which system of coordinates should be used? WGS84, LonLat .... ?

3. Which is the relationship between the z index of the tile and the k scale value?

4. Suppose to have a simple geometry, we want to tile, a flat map, a flat geometry without projection. How can we translate the original coordinates to the coords used by d3? And for the scale?

It would be very useful if there are some documentation or references where to find these information.

thank you for all!

Bye

**Comment by curran** [comment]
Closing as this discourse would be better suited for StackOverflow or the #help channel of the [D3 Slack](https://d3-slackin.herokuapp.com).
