### ISSUE TITLE
Easier tile positioning?

### ISSUE THREAD

**Issue by curran** [d3/d3-tile#5]
Currently, it is a bit cumbersome to set the scale and translate on the tile image container.

``` js
raster.attr("transform", "scale(" + tiles.scale + ")translate(" + tiles.translate + ")");
```

It can be particularly confusing because the scale must come first, which is not that common. It would be nice to be able to say this instead:

``` js
raster.attr("transform", tiles.transform);
```

Here's a [prototype implementation of this](http://bl.ocks.org/curran/defa669c2e7935a91ef5457fe5dd3bc2) where setting the `transform` property on the returned `tiles` array looks like this:

``` js
tiles.transform = d3.zoomIdentity
  .scale(k)
  .translate(x / k, y / k);
```

**Comment by curran** [comment]
Without a dependency on d3-zoom, setting `transform` could look like this:

```js
tiles.transform = {
  k: k,
  x: x / k,
  y: y / k,
  toString: function() {
    return "translate(" + this.x + "," + this.y + ") scale(" + this.k + ")";
  }
};
```

Duplicating [toString from d3-zoom](https://github.com/d3/d3-zoom/blob/master/src/transform.js#L39).

**Comment by curran** [comment]
The implementation could also look like this, a mini d3-zoom transform:

function Transform(k, x, y) {
  this.k = k;
  this.x = x;
  this.y = y;
}

Transform.prototype = {
   toString: function() {
    return "translate(" + this.x + "," + this.y + ") scale(" + this.k + ")";
  }
};
...
/// inside tile(t)
tiles.transform = new Transform(k, x, y);
```

**Comment by curran** [comment]
I noticed this snippet in some of the updated examples, maybe ideas from it could be added into the library.

 * providing `tiles.transform` with scale / 256, intended for direct use with 256 X 256 image elements.
 * The rounding logic for crisp tile boundaries (at least I think that's what that is for..).

```js
function stringify(scale, translate) {
  var k = scale / 256, r = scale % 1 ? Number : Math.round;
  return "translate(" + r(translate[0] * scale) + "," + r(translate[1] * scale) + ") scale(" + k + ")";
}
```

**Comment by mbostock** [comment]
A similar comment, three years later: https://github.com/d3/d3-tile/pull/53#issuecomment-513263755

Adding this issue to 1.0 to see if we can figure out something more convenient.

**Comment by mbostock** [comment]
I’m going to punt on this for 1.0 because I don’t have a great idea for making this easier. The main challenge is that there are many valid ways of rendering tiles, and most of the convenience methods would have to assume a particular rendering method (such as Canvas, or an SVG G with a transform), and I don’t want this library to be overly prescriptive in terms of rendering strategy.
