### ISSUE TITLE
Documentation *very* .... uhm generic, not to say meaningless ;)

### ISSUE THREAD

**Issue by drrho** [d3/d3-tile#50]
What is 'scale', actually?

What is the unit of 'point'? Is it a pixel?

What are the units of 'size' and what is the difference to 'extent'?

Given the myriad of examples for obsolete versions out there, a *precise* documentation
might actually be helpful ....

**Comment by mbostock** [comment]
I don’t think this project is currently being maintained. (At least, it’s not currently being actively maintained by me.) So, the documentation is what it is, but thank you for the feedback.

**Comment by curran** [comment]
I may be able to contribute some time to maintaining this project.

**Comment by drrho** [comment]
> On 05.02.2019, at 07:59, Curran Kelleher <notifications@github.com> wrote:
> 
> I may be able to contribute some time to maintaining this project.
> 

That would be MUCH appreciated. I’m currently trying to amalgamate this somehow with openseadragon.js and
might have to share something at some point.

\rho

**Comment by mbostock** [comment]
For what it’s worth, I have rewritten the documentation and examples as part of the 1.0 release.

https://github.com/d3/d3-tile/blob/master/README.md
https://observablehq.com/collection/@d3/d3-tile
https://observablehq.com/@d3/web-mercator-tiles
