### ISSUE TITLE
tile.tileSize has not been released.

### ISSUE THREAD

**Issue by klattiation** [d3/d3-tile#51]
When importing tile from d3-tile v0.0.4 the tileSize function is missing somehow. It is present in the source file https://github.com/d3/d3-tile/blob/master/src/tile.js and I wonder why it's not available when importing it from node_modules...

```
import { tile } from "d3-tile"

tile().tileSize // <- undefined
```

**Comment by mbostock** [comment]
The tileSize method was merged in #35 but was never released to npm.

**Comment by curran** [comment]
Oh no! My mistake for not releasing a new version on npm.

**Comment by mbostock** [comment]
This is kinda the opposite of *tile*.zoomDelta #9, which is published but not documented. 🤦‍♂

**Comment by mbostock** [comment]
Folding this into #37.
