### ISSUE TITLE
Update examples and documentation for 1.0

### ISSUE THREAD

**Issue by curran** [d3/d3-tile#52]

**Comment by curran** [comment]
thumbnail for [Observable: D3 Vector Tiles](https://observablehq.com/@mbostock/d3-vector-tiles)

![image](https://user-images.githubusercontent.com/68416/54068670-50759200-4275-11e9-9a7a-c1b04636bc3c.png)

**Comment by mbostock** [comment]
I’ll use this issue to track documentation also.

- [x] tile.zoomDelta #9
- [ ] tile.clampX
- [ ] tile.clampY
- [ ] tile.clamp
- [ ] d3.tileWrap
- [ ] tile.wrap (removed)

**Comment by mbostock** [comment]
I have updated the README and all the examples in the d3-tile collection.
