### ISSUE TITLE
Allowing wrapping in y, not just x.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-tile#58]
The API for *tile*.wrap assumes you’d only ever want to wrap in *x*, but we should also allow wrapping in *y* (e.g., for transverse Mercator). In general, this library shouldn’t make any assumptions about geographic coordinates; it’s a planar tile quadtree.

I propose we remove *tile*.wrap and replace it with *tile*.wrapX and *tile*.wrapY for 1.0.

**Comment by mbostock** [comment]
I’ve added *tile*.clampX, *tile*.clampY and *tile*.clamp to control which tiles are visible (allowing *x* and *y* to go outside the “world”). I need to restore a mechanism for computing the wrapped tile coordinates now, though.

**Comment by mbostock** [comment]
Added d3.tileWrap in 860e06620e57d49617795546aadf079d0da3d58c.

**Comment by curran** [comment]
Hooray! What an idea.
