### ISSUE TITLE
Can't zoom out to scale < 1 ?

### ISSUE THREAD

**Issue by Fil** [d3/d3-tile#59]
If I want a tiny map of less than 256px, the current code returns tiles.scale = 256.

Not sure if this is a feature. It makes it more difficult to use in some cases where you want the map to fit a tiny square for some reason (for example in https://observablehq.com/d/8f96daba13b5347a ).

**Comment by Fil** [comment]
By "scale < 1" I meant, relative to the tiles' size, so the tile would be displayed smaller than it is.

See https://observablehq.com/d/c9059efda12fea8b for a solution around this issue.

**Comment by mbostock** [comment]
Yeah, this is a bug. It should be possible to set the minimum scale in the zoomable map tile notebook to 1 and it should just keep making the world tile smaller and smaller.

**Comment by mbostock** [comment]
This should be fixed in d3-tile 1.0 if you want to update your notebook.

Also, the technique of having multiple layers to fix the flickering on zoom looks great! I’m wondering if you can implement that using *tile*.zoomDelta? (Namely two layers with delta -1 and -2.) See this demo: https://observablehq.com/@d3/tile-zoomdelta

**Comment by Fil** [comment]
Same approach but a cleaner code, using zoomDelta:
https://observablehq.com/@fil/seamless-zoomable-map-tiles

**Comment by mbostock** [comment]
I’m surprised by how well that seamless approach works! Looks great!

I think you could also combine them into a single layer and then you wouldn’t need to replace the tiles on zooming. But you’d have to still get the order of tiles by zoom delta correct so that zoom delta zero is on top.

**Comment by Fil** [comment]
Ordering is not a problem, but tiles.translate does not live in the tile,
so there's a little juggling to do with the data. I wanted to stay close to
the original in that regard, but if there is a better way, let's do it :)

>

**Comment by mbostock** [comment]
Ah, yes, that makes sense. Thanks for the explanation!
