### ISSUE TITLE
Basic Image API

### ISSUE THREAD

**Issue by curran** [d3/d3-tile#7]
Create a basic API that wraps the image logic from existing examples.

Part of #3

**Comment by curran** [comment]
Here's a [prototype implementation](http://bl.ocks.org/curran/bc4f13b6ff84c65820b9026a3d1fa8ce) of `d3.tileImage`.

**Comment by curran** [comment]
Here's another [example](http://bl.ocks.org/curran/96823ad84b0415536980b1cbf57b1dcc) that shows two tile layers.

[![image](https://cloud.githubusercontent.com/assets/68416/16310563/a8f65028-398a-11e6-99e1-fa791da9e897.png)](http://bl.ocks.org/curran/96823ad84b0415536980b1cbf57b1dcc)

**Comment by curran** [comment]
I noticed that when using the approach of 1 X 1 pixel SVG images for tiles, the behavior when zoomed into fine details is a bit strange. Here's an [example](http://bl.ocks.org/curran/dc6d8f6e1e194e20e053071add2d481c).

When zooming in and out, the tiles jitter back and forth. It seems like it might be floating point error. I wonder if this would be solved by using 256 X 256 SVG images instead of 1 X 1, so the transforms are less extreme...

**Comment by curran** [comment]
After changes from #13, it could look like this:

```js
function tileImages(tile){
  var url = d3.tileProviders.openStreetMap;
  var images = function (raster){
    var tiles = tile();

    var image = raster
        .attr("transform", tiles.transform)
      .selectAll("image")
        .data(tiles, function(d) { return d; });

    image.exit()
        .remove();

    image.enter().append("image")
        .attr("xlink:href", url)
        .attr("width", 256)
        .attr("height", 256)
      .merge(image)
        .attr("x", function(d) { return d.x; })
        .attr("y", function(d) { return d.y; });
  };
  
  images.url = function (_){
    return arguments.length ? (url = _, images) : url;
  }
  
  return images;
}

**Comment by Fil** [comment]
Maybe this could be expanded to have two modes: `svg` (`g + image`) and `html` (`div + img`).

**Comment by mbostock** [comment]
Closing this to inactivity, and also because it feels like a higher-level API might belong better as a separate module. The low-level nature of d3.tile is a differentiator versus other high-level tiling APIs such as Leaflet.
