### ISSUE TITLE
URL Templates

### ISSUE THREAD

**Issue by curran** [d3/d3-tile#8]
This module could provide an API for working with URL template strings like 'http://{s}.tile.osm.org/{z}/{x}/{y}.png'. This would make it easy to use different tile providers based on declarative data, like in this [Leaflet Providers Demo](https://leaflet-extras.github.io/leaflet-providers/preview/).

Such an API can help with the issue of caching tiles. As an example, [Raster & Vector III](http://bl.ocks.org/mbostock/5914438) has the behavior of re-loading the same tiles again and again, due to the randomness introduced in the URL generation. I think this issue would be solved by deterministic URL generation, leaving the actual caching up to the browser.

Leaflet has an implementation of this URL template logic. See [Leaflet URL Template Docs](http://leafletjs.com/reference.html#url-template).

Split out from #3.

**Comment by curran** [comment]
Here's a [prototype implementation](http://bl.ocks.org/curran/6d09e00a18aebc2623843a65181089d1).

```js
function tileUrl(pattern){
  return function (d){
    return pattern
      .replace("{x}", d[0])
      .replace("{y}", d[1])
      .replace("{z}", d[2])
      .replace("{s}", ["a", "b", "c"][Math.random() * 3 | 0]);
  };
}
```

**Comment by curran** [comment]
Oh wow, what a great idea! I was imagining something more complicated like memoizing the random number, but this is a great solution.

So the general implementation could look like this:

```
function tileUrl(pattern){
  return function (d){
    return pattern
      .replace("{x}", d[0])
      .replace("{y}", d[1])
      .replace("{z}", d[2])
      .replace("{s}", "abc"[d[1] % 3]);
  };
}
```

I noticed in Leaflet there is a parameter to specify the list of subdomains, so the even more general version could look like this:


```
function tileUrl(pattern, subdomains){
  return function (d){
    return pattern
      .replace("{x}", d[0])
      .replace("{y}", d[1])
      .replace("{z}", d[2])
      .replace("{s}", subdomains[d[1] % subdomains.length]);
  };
}
```

**Comment by mbostock** [comment]
That’s not a general solution because the available hosts tends to vary; it’s not always {a, b, c}. But I suppose you could do this:

```js
function tileUrl(pattern, hosts) {
  return function(d) {
    return pattern
        .replace("{x}", d[0])
        .replace("{y}", d[1])
        .replace("{z}", d[2])
        .replace("{s}", hosts[d[1] % hosts.length]);
  };
}
```

And then

```js
var labels = tileUrl("http://stamen-tiles-{s}.a.ssl.fastly.net/toner-labels/{z}/{x}/{y}.png", ["a", "b", "c"]);
```

Although it’d be neat if you could somehow include that in the format automatically, like, I dunno…

```js
var labels = tileUrl("http://stamen-tiles-{a,b,c}.a.ssl.fastly.net/toner-labels/%z/%x/%y.png");
```

Curl does fancy stuff like this for concise expression of multiple related URLS:

https://curl.haxx.se/docs/manpage.html

But, it doesn’t also have the concept of named parameters that you can substitute in a URL.

Of course there is also JavaScript [string templates](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals), so, not sure you really need much of an abstraction:

```js
function labels(x, y, z) {
  return `http://stamen-tiles-${"abc"[x % 3]}.a.ssl.fastly.net/toner-labels/${z}/${x}/${y}.png`;
}
```

**Comment by curran** [comment]
I like the idea of being able to encode the list of hosts inside the template itself.

From Curl:

```
or you can get sequences of alphanumeric series by using [] as in:
...
  ftp://ftp.example.com/file[a-z].txt
```

It might be nice to keep the `{z}/{x}/{y}` convention from Leaflet, and also use the `[a-z]` syntax from Curl, which is more concise than specifying a whole array, resulting in something like

```js
tileUrl("http://stamen-tiles-[a-c].a.ssl.fastly.net/toner-labels/{z}/{x}/{y}.png");
```

Maybe an alternative for specifying domains that don't fall in a simple sequence could be


```js
tileUrl("http://stamen-tiles-[a,b,c].a.ssl.fastly.net/toner-labels/{z}/{x}/{y}.png");
```

**Comment by mbostock** [comment]
Closing to inactivity, and also I think string templates are pretty good out of the box for this. You can see some examples in this notebook if you click *Edit* in the cell menu next to the drop-down menu of tile providers. 

https://observablehq.com/@d3/raster-tiles
