### ISSUE TITLE
tile.zoomDelta is undocumented.

### ISSUE THREAD

**Issue by curran** [d3/d3-tile#9]
Add documentation for zoomDelta.

**Comment by Ethanjfriedman** [comment]
Some documentation on zoomDelta and how it works would be terrific. I am attempting to use d3-tile now and having to go via trial and error since I am not finding other docs or examples that make use of this version.

**Comment by curran** [comment]
Researching this a bit, and here's what I found:

Demos related to `zoomDelta`:

 * https://observablehq.com/@mbostock/a-map-of-every-building
 * http://bl.ocks.org/mbostock/4150951

From #2:

>It’s for showing tiles at different resolution than the screen. For example, if you have a HiDPI screen, you might take 256×256 tiles and display them in a 128×128 space.

**Comment by curran** [comment]
I put this together for the documentation:

![image](https://user-images.githubusercontent.com/68416/61864415-03761d80-aeef-11e9-8c03-b772df649f72.png)

https://observablehq.com/d/6acb6597d1d35e6d

It would be cool to put them next to each other programmatically, but I haven't figured out the Observable syntax/API for having multiple SVG elements in a div.

**Comment by mbostock** [comment]
Your notebook is private; can you click the notebook menu (the three horizontal dots in the header) and click on “Enable link sharing” so I can see it?

**Comment by curran** [comment]
Oops! Should be visible now https://observablehq.com/d/6acb6597d1d35e6d

**Comment by mbostock** [comment]
Ah, looks nearly identical to my approach, although I used a function to avoid duplicating the code. Great minds think alike? :wink:

https://observablehq.com/@d3/tile-zoomdelta
